### ISSUE TITLE
Problems using it with Dockerfile

### ISSUE THREAD

**Issue by imgios** [AkhileshNS/heroku-deploy#102]
I've been running the workflow for about 1h or so (and it's still running) but the action doesn't start/end.

This is the workflow:
```YAML
name: Deploy in Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nonnatittina-bot"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: TG_BOT_TOKEN
        env:
          TG_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
```

And this is the Dockerfile:
```dockerfile
FROM python:3

ARG TG_BOT_TOKEN

ENV TELEGRAM_BOT_TOKEN=$TG_BOT_TOKEN
WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python bot.py

CMD ["python", "./bot.py"]
```

Manually deploy from the Heroku Dashboard (attaching the app with the repository) works. Am I doing something wrong?
