### ISSUE TITLE
Deploy step is being skipped when the action is ran

### ISSUE THREAD

**Issue by joaocasarin** [AkhileshNS/heroku-deploy#103]
Well I have just created a github action for my repo and every step pass, except the one that uses this heroku-deploy. It just skips.

This is the code:
```yaml
      - name: Deploy the project
        if: ${{github.ref == 'regs/heads/main'}}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "testjvcapi"
          heroku_email: "joaovitorcasarin@hotmail.com"
          buildpack: "https://github.com/zidizei/heroku-buildpack-tsc#v2.0"
```

And this is the output:
![image](https://user-images.githubusercontent.com/48847394/138162111-5a993761-4689-40ac-b440-a2ae09bafdfc.png)

What else should be done to make it to deploy?
Link to the action: https://github.com/joaocasarin/test-selfapi/actions/runs/1365090226
