### ISSUE TITLE
Hi have same error. I tried to add this line of code  run: git add -A && git commit -m "Updated code" # <- Add this line  but I obtain a message that there is nothing to commit and so, I remove the line. This is my yaml file:  name: Deploy  on: [push]    jobs:   build:     runs-on: ubuntu-latest     steps:       - uses: actions/checkout@v2       - name: install         run: npm i                - name: test         run: npm run test-git        - name: Setup         run: mkdir -p dist        - name: build         run: npm run build-full                        - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action         with:           heroku_api_key: ${{secrets.HEROKU_API_KEY}}           heroku_app_name: "heroku-app-name" #Must be unique in Heroku           heroku_email: "myemail@email.com"                     appdir: "dist"

### ISSUE THREAD

**Issue by PietroRove** [AkhileshNS/heroku-deploy#106]
Hi have same error. I tried to add this line of code

run: git add -A && git commit -m "Updated code" # <- Add this line

but I obtain a message that there is nothing to commit and so, I remove the line. This is my yaml file:

name: Deploy

on: [push]
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm i
        
      - name: test
        run: npm run test-git

      - name: Setup
        run: mkdir -p dist

      - name: build
        run: npm run build-full
                
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "heroku-app-name" #Must be unique in Heroku
          heroku_email: "myemail@email.com"          
          appdir: "dist"

**Comment by cansin** [comment]
We were having a similar issue (if not the same). Turns out we forgot to add our bot account to the Heroku application (with Deploy access). Doing that, plus the below `deploy.yml` works for us currently:

```yml
name: Deploy

concurrency:
  group: deploy
  cancel-in-progress: false

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy code
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sample-app-name"
          heroku_email: "bot@sample.com"
          team: "sample-team"
          dontuseforce: true
          dontautocreate: true
```

Hope this helps someone.
