### ISSUE TITLE
When Heroku deploy fails action does not fail

### ISSUE THREAD

**Issue by hidr0** [AkhileshNS/heroku-deploy#108]
```
  release:
    if: github.ref == 'refs/heads/main'
    name: "Release"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
```
![Screenshot 2021-11-17 at 15 27 41](https://user-images.githubusercontent.com/5238203/142209704-f5f5c009-2fd3-4cab-bb5e-6ddbe3e9f76a.png)
