### ISSUE TITLE
How do I deploy to a different heroku app?

### ISSUE THREAD

**Issue by mattfrancis888** [AkhileshNS/heroku-deploy#109]
Here is how I am pushing it to my heroku app when I make changes on main. However, how do I deloy it to a different herolu app (say gh-actions-uat)  when I make changes on development branch?
```
name: Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2  
            - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "gh-actions-uat" #Must be unique in Heroku
                  heroku_email: "a888@gmail.com"
```
