### ISSUE TITLE
Missing refs/heads/master on git push with appdir (Heroku + Git error)

### ISSUE THREAD

**Issue by Jakobo** [AkhileshNS/heroku-deploy#11]
## Summary
When performing an app's first push to Heroku, the action will fail due to Heroku not having a `master` ref to push to. I believe we probably need to explicitly push to `refs/heads/master` since it doesn't exist yet on the Heroku side until that first push.

Once you've made (any) initial first push to the repository, the action works as expected.

**Update** Looks to be https://github.com/AkhileshNS/heroku-deploy/blob/master/index.js#L25 which just guesses `master` which is incorrect for an initial push.

**Can Pull Request** ✅  I'm happy to put together a PR for this issue

## Steps to Reproduce
1. Create an app in heroku, but don't push anything to it yet
2. Set up your heroku step using the yaml
```
- name: Deploying to Heroku
  uses: akhileshns/heroku-deploy@v3.0.2
  with:
    heroku_api_key: ${{secrets.HEROKU_API_KEY}}
    heroku_app_name: APP_NAME # change to your app
    heroku_email: ${{secrets.HEROKU_EMAIL}}
    appdir: services/SUBFOLDER # subfolder used here
```
3. Run the action

**Expected Result**
* First push to Heroku succeeds, detects buildpack, procfile, etc

**Actual Result**
```
Error: Command failed: git push --force heroku `git subtree split --prefix=services/SUBFOLDER HEAD`:master
1/1384 (0) [0]
2/1384 (1) [0]
3/1384 (2) [0]
4/1384 (3) [0]
... # lines skipped
1383/1384 (1382) [120]
1384/1384 (1383) [120]
error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:

- Looking for a ref that matches 'master' on the remote side.
- Checking if the <src> being pushed ('31fd----------')
  is a ref in "refs/{heads,tags}/". If so we add a corresponding
  refs/{heads,tags}/ prefix on the remote side.

Neither worked, so we gave up. You must fully qualify the ref.
hint: The <src> part of the refspec is a commit object.
hint: Did you mean to create a new branch by pushing to
hint: '31fd----------:refs/heads/master'?
error: failed to push some refs to 'https://git.heroku.com/APP_NAME.git'
```

## Additional Context
I was able to verify that the action works after manually making an initial "first push" to set a buildpack etc. It might be easier to tell people not to create the app on Heroku's side if they want a successful first push.

In the above example, I've removed sensitive information from GH Action log output.

Edits:
* For clarity, cleaned up the action yaml to remove the app name I was pushing to
