### ISSUE TITLE
can't deploy with Docker

### ISSUE THREAD

**Issue by fangxingweiai** [AkhileshNS/heroku-deploy#111]
```yaml
  heroku-deploy:
    if: ${{ github.event.inputs.actions == 'deploy' || github.event.inputs.actions == ''}}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    steps:
      - run: echo APP_NAME is ${{secrets.APP_NAME}}
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.EMAIL}}
          usedocker: true
```

## log
![image](https://user-images.githubusercontent.com/62201630/144667906-40b48d9a-657e-4718-a412-49a5b7ad771e.png)
