### ISSUE TITLE
[BUG] could not read Username for 'https://github.com'

### ISSUE THREAD

**Issue by GrassBlock1** [AkhileshNS/heroku-deploy#113]
First of all thanks for creating this awesome github action!
I am a bit new to this ecosystem so forgive me :bow:

I have it used with a private repo ,  but when I pushed to master , I got error and saw these logs:
```
fatal: could not read Username for 'https://github.com/': No such device or address
Error: Error: Command failed: git fetch --prune --unshallow
fatal: could not read Username for 'https://github.com/': No such device or address
```

And here is my workflow file:
 <details markdown="true">

```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "grassblogx" #Must be unique in Heroku
          heroku_email: "(email is hidden but it's right)"

```

</details>

Maybe caused by using HTTP access? I don't know really, any solutions?
