### ISSUE TITLE
Not all env_file variables are set

### ISSUE THREAD

**Issue by susannakosic** [AkhileshNS/heroku-deploy#114]
Hi,
I m using this action to deploy a monorepo to heroku.
See below config for api deployment:
```
- name: Deploy server
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sga-s"
          heroku_email: ${{secrets.HEROKU_API_KEY}}
          env_file: ".env.prod"
        env:
          HD_APP_BASE: "components/server"
```
.env.prod file contains a bunch of env vars:
```
OAUTH_ENABLED=true
SGA_S_HOST=bah
SGA_SPA=buh
OAUTH_DOMAIN=bah
OAUTH_CLIENT_ID=buh buh
OAUTH_JWKS_URI=buh buh
OAUTH_AUDIENCE=buh buh
CORS_ORIGINS=bah
MONGO=buh buh
NODE_ENV=production
USERNAME_KEY=buh buh
LOG_LEVEL=info
```
However once the job is done, I can only see a subset of this vars being set. Those are:
```
OAUTH_ENABLED=true
SGA_S_HOST=bah
SGA_SPA=buh
OAUTH_DOMAIN=bah
OAUTH_CLIENT_ID=buh buh
OAUTH_JWKS_URI=buh buh
OAUTH_AUDIENCE=buh buh
CORS_ORIGINS=bah
MONGO=buh buh
```
I've manually deleted the env vars from the heroku app and redeployed, still got the same behaviour. Any idea why this could be happening?
