### ISSUE TITLE
Deploy Only For Commits On A Particular File

### ISSUE THREAD

**Issue by Pysics** [AkhileshNS/heroku-deploy#120]
How can I do this?

**Comment by tomaswarynyca** [comment]
It is not related to this action, it is related to github workflow.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths

**Comment by Pysics** [comment]
@tomaswarynyca This doesn't seem to work:
```yml
on:
  push:
    branches:
      - master
    paths:
      - 'main.py'
```
