### ISSUE TITLE
Error: Error: Command failed: git add -A && git commit -m "Commited changes from previous actions"

### ISSUE THREAD

**Issue by see** [AkhileshNS/heroku-deploy#121]
```
name: Deploy To Heroku

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: true

      - name: Deploy To Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_TS}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          procfile: ${{secrets.HEROKU_PROCFILE}}
          env_file: '.env'

```
