### ISSUE TITLE
BUG: workflow stopped working today morning

### ISSUE THREAD

**Issue by Toumash** [AkhileshNS/heroku-deploy#134]
```
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Configuration
```
name: Deploy API

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} # get it from heroku account settings - https://dashboard.heroku.com/account
          heroku_app_name: "some_app"
          heroku_email: "someemail@gmail.com"
          appdir: "api"
```
