### ISSUE TITLE
Retrieving the logs takes ages

### ISSUE THREAD

**Issue by marcellussiegburg** [AkhileshNS/heroku-deploy#15]
I have a build process which takes a very long time to build on Heroku (nearly 30 Minutes). After the build finished I saw that the Github Action was still running. I aborted the action at (42m 22s running time). The action was in midst of printing line 931. The complete log was 6663 lines long.

This could be somewhat related to #5?

**Comment by AkhileshNS** [comment]
Hey, sorry for replying so late (different Timezone). If its alright, could you maybe post the action.yml file you are using. It would easier to diagnose your issue with that.

Also note that the only logs which the action specifically puts are one liners. All other logs come from Heroku and Git, so I would try comparing what the action is doing to what the heroku cli is doing on your local machine to see if you can find your logs, and then maybe we can add an additional option to the action that will let you filter logs.

Regarding the performance of the action, an update has been long overdue as the date on #5 would suggest. These past few months with the pandemic have made it slightly difficult, but I should have some performance improvements coming in around a week max. Hopefully that will help with your issue

**Comment by marcellussiegburg** [comment]
Sorry for the delayed reply.

This ist the action.yml:
```yaml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: "https://github.com/mfine/heroku-buildpack-stack.git"
          dontuseforce: false
          usedocker: false
          appdir: ""
```
I gave this some thought.
Maybe redirecting the output to a specific file would be an option?
This could be reused as artifact (https://github.com/marketplace/actions/upload-a-build-artifact) or in other ways by following steps. Thus it would be up to the user of your library. This would at least help, if printing the log is the issue here.
