### ISSUE TITLE
heroku: Press any key to open up the browser to login or q to exit

### ISSUE THREAD

**Issue by carlosLMZarego** [AkhileshNS/heroku-deploy#153]
Hi, my action is failing now because in my CD Heroku ask for credentials...

```
Heroku: Press any key to open up the browser to login or q to exit: fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'Heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

```
why is this asking for credentials when this should use the API key?...

thank you

**Comment by carlosLMZarego** [comment]
this is my yalconfigloy

```yml
name: Push Container to Heroku

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: "development"

```

**Comment by carlosLMZarego** [comment]
adding the  justlogin: true fix the issue

```
 with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ""
          heroku_email: "YOUR EMAIL"
          justlogin: true
```

**Comment by carlosLMZarego** [comment]
adding the fix the issue

```
 with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ""
          heroku_email: "YOUR EMAIL"
          justlogin: true
```
