### ISSUE TITLE
Update README to use nodejs 16

### ISSUE THREAD

**Issue by elibroftw** [AkhileshNS/heroku-deploy#159]
The current readme uses actionv2 which uses nodejs 12.

I suggest the following (untested)

```yml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "slug"
          heroku_email: "NAME@DOMAIN.COM"

```
