### ISSUE TITLE
Failing shows as success

### ISSUE THREAD

**Issue by Francescu** [AkhileshNS/heroku-deploy#16]
Hi 👋

When the step fails, it shows up as a success, cf. screenshot:

![image](https://user-images.githubusercontent.com/1433362/83022062-403d0480-a02b-11ea-8b65-5d98d22bf768.png)

**Comment by AkhileshNS** [comment]
Hey really sorry for the late response. I'm not sure exactly why it's ignoring the error. But as a fix, the logs do suggest adding `git pull` step before the action so I would recommend you try and that let me know if it works. Your final yaml file might look something like this

```yaml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git pull # <- Add this step
      - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "YOUR APP's NAME" #Must be unique in Heroku
          heroku_email: "YOUR EMAIL"
```
