### ISSUE TITLE
Deployments "silently" fail after v4 update: `remote: Pushed to branch other than [main, master], skipping build.`

### ISSUE THREAD

**Issue by viamin** [AkhileshNS/heroku-deploy#176]
I'm seeing this in my Github Action output after updating to v4:
```
STEP: Adding Remote - Success
STEP: Adding Configuration Variables from env and envfile - Success
remote: Pushed to branch other than [main, master], skipping build.        
To https://git.heroku.com/myapp-production.git
   5f84f2f7..62b983be  main -> refs/head/main
STEP: Deploying - Success
default: PASSED Application is running (0.000s)
STEP: Performing HealthCheck - Success
```

This is (basically) what my deployment workflow step looks like:
```
  deploy-production:
    needs: [test, lint, deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Production
        uses: akhileshns/heroku-deploy@v4
        with:
          heroku_app_name: "myapp-production"
          heroku_email: "<my email>"
          heroku_api_key: "${{secrets.HEROKU_API_KEY}}"
          healthcheck: "https://myapp.com/okcomputer"
          delay: 20
          rollbackonhealthcheckfailed: true
```

**Comment by karlentwistle** [comment]
Also facing the same problem switching from 3.13.15 to 4

```
  deploy:
    runs-on: ubuntu-latest
    concurrency: production-deploy
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v4
        with:
          heroku_email: ${{ secrets.HEROKU_DEPLOY_USER }}
          heroku_api_key: ${{ secrets.HEROKU_DEPLOY_KEY }}
          heroku_app_name: "myapp-production"

```
