### ISSUE TITLE
docker_build_args not working 

### ISSUE THREAD

**Issue by stroncod** [AkhileshNS/heroku-deploy#179]
My deploy.yml looks like this: 

```
name: Deploy to Heroku
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build, Push and Release a Docker container to Heroku.
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          # Below you must provide variables for your Heroku app.

          # The email address associated with your Heroku account.
          # If you don't want to use repository secrets (which is recommended) you can do:
          # email: my.email@example.com
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          
          # Heroku API key associated with provided user's email.
          # Api Key is available under your Heroku account settings.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          
          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          usedocker: true
          docker_build_args: |
            GH_PAT
            TEST_VAL
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          TEST_VAL: value
```

But when I run the workflow and I called in the dockerfile:
```
RUN echo "TEST_VAL=${TEST_VAL}"
```

It prints just `TEST_VAL=`so basically is not setting up the args from env.
