### ISSUE TITLE
/bin/sh: 1: heroku: not found

### ISSUE THREAD

**Issue by mariuswestgaard** [AkhileshNS/heroku-deploy#184]
I've suddenly started seeing this error on my github actions pipeline: `/bin/sh: 1: heroku: not found`

I did not change my workflow .yml file, and it suddenly started happening today (had a successful deploy yesterday).

System:
Rails version: 7.1.3
Ruby version: 3.2.3
Node version: 20

Here's the workflow that fails:
```deploy-production:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/production'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Heroku CLI
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: <<secret>>
          heroku_app_name: '<<app-name>>'
          heroku_email: '<<example@test.com>>'
```

I'm wondering what could have changed and how to fix it? My first thought was, I'm not specifying actions/checkout version in this file, so maybe this could have been the cause in some way. I've then tested multiple versions (4.0.0 and 4.1.7) even though the "Checkout Repository" step works. Same error with every version tested.

Then, I thought maybe it's the ubuntu-latest that is now changed. But, I looked at https://github.com/actions/runner-images and the current ubuntu-latest (which is [ubuntu-24.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md)), this version has node 20, which should align with my apps node-version and `akhileshns/heroku-deploy@v3.13.15` if I'm not mistaking.

Do you have any clue what might have happened here?

------

Console log:

```
Run akhileshns/heroku-deploy@v3.13.15
  with:
    heroku_api_key: ***
    heroku_app_name: <<app-name>>
    heroku_email: <<example@test.com>>
    branch: HEAD
    dontuseforce: false
    dontautocreate: false
    usedocker: false
    docker_heroku_process_type: web
    delay: 0
    rollbackonhealthcheckfailed: false
    justlogin: false
From <<git-repo>>
...
Created and wrote to ~/.netrc
Successfully logged into heroku
/bin/sh: 1: heroku: not found
/bin/sh: 1: heroku: not found
Error: Error: Command failed: heroku create <<app-name>>
/bin/sh: 1: heroku: not found
```

**Comment by fmaturanaa** [comment]
Same here, I didn't change anything and the action starts to fail. Anyone knows how to fix it?

**Comment by joewoodhouse** [comment]
@fmaturanaa hit same issue, see https://github.com/AkhileshNS/heroku-deploy/commit/e86b991436e126ff9d78399b801a6610a64881c9

**Comment by TomAndreFossen** [comment]
We are also having this issue. Any hint to what is causing this? We are using a fork and nothing has changed on our side, is there any change done to Heroku causing this?

**Comment by joewoodhouse** [comment]
@TomAndreFossen see https://github.com/AkhileshNS/heroku-deploy/issues/184#issuecomment-2412328428

**Comment by mariuswestgaard** [comment]
@joewoodhouse Thanks! You're right. Adding the heroku cli (as explained in the commit you linked), manually before the heroku-deploy step works great.

Here's the updated workflow for anyone with the same issue:

```
deploy-production:
    needs: test
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' && github.ref == 'refs/heads/production'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: 'Install Heroku CLI'
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - name: Set Up Heroku CLI
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: <<secret>>
          heroku_app_name: '<<app-name>>'
          heroku_email: '<<example@test.com>>'

```
