### ISSUE TITLE
heroku command suddenly not found

### ISSUE THREAD

**Issue by tillpd** [AkhileshNS/heroku-deploy#185]
My Github Action was working fine, but on the last run I received this error:
`/home/runner/work/_temp/052a0109-6c74-4251-9686-ddd55b29dbdf.sh: line 2: heroku: command not found`

I didn't change anything. Here are my steps:
```

  - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          justlogin: true

   - name: Build docker image
        if: env.deploy == 'true'
        run: |
          heroku container:login
         .....
```
