### ISSUE TITLE
heroku: not found

### ISSUE THREAD

**Issue by timimsms** [AkhileshNS/heroku-deploy#186]
Running into an issue where the action doesn't seem to recognize Heroku as a valid command.

````
From https://github.com/HootMedical/hoot-web
...
Created and wrote to ~/.netrc
Successfully logged into heroku
/bin/sh: 1: heroku: not found
/bin/sh: 1: heroku: not found
Error: Error: Command failed: heroku create hoot-web-staging
/bin/sh: 1: heroku: not found
````

Section of config:
````yaml
      # Heroku: (deploy) develop -> staging
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          heroku_app_name: ${{ env.HERKOU_SERVER }}
          branch: develop
          healthcheck: ${{ env.HEROKU_HEALTH }}
````

Using [akhileshns/heroku-deploy@v3.12.12 ](https://github.com/AkhileshNS/heroku-deploy/releases/tag/v3.12.12)
