### ISSUE TITLE
Impossible to deploy on heroku

### ISSUE THREAD

**Issue by nik7007** [AkhileshNS/heroku-deploy#188]
Our GitHub action crashes due to the following error:

```
/bin/sh: 1: heroku: not found
/bin/sh: 1: heroku: not found
Created and wrote to ~/.netrc
Successfully logged into heroku
Error: Error: Command failed: heroku create med-futura
/bin/sh: 1: heroku: not found
```
The action is:

```
name: Deploy to Heroku

on:
  release:
    types: [created]

jobs:
  build-med:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.13.15 # This action deploys to Heroku
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "med-futura" 
        heroku_email: ${{secrets.HEROKU_EMAIL}}
```
