### ISSUE TITLE
Variable to pass Procfile. 

### ISSUE THREAD

**Issue by sgeek017** [AkhileshNS/heroku-deploy#19]
Is it possible to add the procfile values to pass as variable instead of default?

**Comment by AkhileshNS** [comment]
Hey sorry but I'm not sure I quite understand what you mean. Are you saying add an option where you pass the content of the Procfile as an option in the action sort of like this:-

```yaml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.5 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "YOUR APP's NAME" #Must be unique in Heroku
          heroku_email: "YOUR EMAIL"
          procfile: "web: npm start"
```

If this is what you are suggesting then while it would help remove the need for an additional file just for a few lines of code, I want to try and keep the number of options for the Action as few as necessary because too many options might be confusing to some people, additionally it might cause compatibility issues if someone decides to stop using the action for some reason and switches back to the cli. 

Lemme know if I'm wrong in any way
