### ISSUE TITLE
Error on pushing to heroku

### ISSUE THREAD

**Issue by jotamusik** [AkhileshNS/heroku-deploy#2]
I'm using this action and I have the following error message while the aciton tries to push to heroku.

```
remote: !	Push rejected, source repository is a shallow clone. Unshallow it with `git fetch --all --unshallow` and try pushing again.
remote:
To https://git.heroku.com/laborsord.git
 ! [remote rejected] HEAD -> master (shallow update not allowed)
error: failed to push some refs to 'https://git.heroku.com/laborsord.git'
##[error]Error: Command failed: git push heroku HEAD:refs/heads/master
```

**Comment by AkhileshNS** [comment]
According to [this](https://devcenter.heroku.com/changelog-items/775), Heroku is automatically rejecting shallow clones of repos. On that note, try doing what the error suggests you to do, add `git fetch --all --unshallow` before pushing your code.

So in your main.yml inside your .github/workflows folder: 
```yaml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - run: git fetch --all --unshallow # ADD THIS LINE
        - uses: akhileshns/heroku-deploy@master
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "YOUR APP's NAME (must be unique to heroku)"
            heroku_email: "YOUR EMAIL"
            buildpack: "SOME BUILDPACK [OPTIONAL]"
```

As the command suggests, it should technically convert your shallow clone to an unshallow one. But if that still doesn't work, then can you try sending your entire main.yml if its not too much trouble

**Comment by AkhileshNS** [comment]
Actually I think I found the problem, in the official docs for the actions/checkout@v1 github action, it says

![fetch deep](https://user-images.githubusercontent.com/21128574/72272328-74042880-364e-11ea-982d-2daf1d6c8c27.png)

The second line says that by default, the action only fetches one commit. That could be the reason why the clone is coming off as a shallow one. To fix this, try adding the following line in your main.yml inside your .github/workflows folder:-

```yaml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
          with:             # ADD THIS LINE
            fetch-depth: 0  # ADD THIS LINE
        - uses: akhileshns/heroku-deploy@master
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "YOUR APP's NAME (must be unique to heroku)"
            heroku_email: "YOUR EMAIL"
            buildpack: "SOME BUILDPACK [OPTIONAL]"
```

And hopefully that fixes it

**Comment by jotamusik** [comment]
I have solved by this! Thanks! :P

**Comment by balexandre** [comment]
I'm having almost the same issue:

```yml
name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v1
#      with:
#        node-version: ${{ matrix.node-version }}
#    - name: npm install, build, and test
#      run: |
#        npm ci
#        npm run build --if-present
#        npm test
#      env:
#        CI: true
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v2.0.2
      with:
        # This will be used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{ secrets.HEROKU_USER_AUTH }}
        # Email that you use with heroku
        heroku_email: ${{ secrets.HEROKU_USER_EMAIL }}
        # The appname to use for deploying/updating
        heroku_app_name: ba-registrations
        branch: master
```

but I'm getting

```
Error: Command failed: git fetch --prune --unshallow
fatal: --unshallow on a complete repository does not make sense
```

![](https://i.imgur.com/4lUyLW7.png)

Any idea what am I doing wrong?

P.S. Heroku already has a version of the code, it's not a new application, I just created the repo in GitHub and wanted to make an action to deploy it automagically

**Comment by AkhileshNS** [comment]
Alright so to fix this problem, all you wanna do is switch the version of actions/checkout from `v1` to `v2` and remove the fetch-depth option

```yml
# ...
jobs:
  build:
    steps:
      - uses: actions/checkout@v2 # from v1 and no with: fetch-depth: 0
# ...
```

And to try and explain to you the problem, originally in v1 of the actions/checkout, the action was making a complete clone of the repo (or an unshallow clone) but later on in v2, the team at github decided to make the action perform shallow clones instead (and that's what started this issue in the first place). So to try and circumvent, I decided to add the 

```git
git fetch --prune --unshallow
```

command as built into this action's (heroku-deploy) code. But now the action only works on shallow clones 😅 (since the action makes them unshallow anyway). I did this because I suspected most people would use v2 of the actions/checkout action and wouldn't think to add the fetch-depth: 0 flag so by having unshallowing built into the heroku-deploy action, they wouldn't even need to think about it. But its pretty clear now I'll need to work on a more elegant situation which I will do in the next release.

FOR THE TIMEBEING THOUGH, FOR ANY FUTURE USERS RUNNING INTO THIS ISSUE, make sure that you are using `v2` of the actions/checkout action and you have not set the fetch-depth: 0 flag exactly as given in the documentation. I'm gonna try adding the shallow and unshallowing issues in the docs as well (atleast until I can find a way to circumvent it)

P.S @balexandre sorry for the late reply, I suspect we live in different timezones and I was asleep when you commented
