### ISSUE TITLE
[Feature request] post-deploy Health check 

### ISSUE THREAD

**Issue by tinacious** [AkhileshNS/heroku-deploy#20]
First, I'd like to say thank you to all the collaborators involved in making this Github Action. 🙏 

I think a great feature would be to do a quick health check to verify that a provided endpoint returns GET 200 OK otherwise fail the build.

It would be great if this could be optionally configured at the action level in the yaml file alongside the other `with` variables.

This feature would address the case that the code deploys correctly but the application does not start.

This feature would **not** address the case that the code fails to deploy due to a git error as it would stop a build attempt since the code didn't get updated, so the issue described [here](https://github.com/AkhileshNS/heroku-deploy/issues/16) would be a separate issue.

Here's an example ideal usage:

```yml
name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    - uses: actions/checkout@v2
    - uses: AkhileshNS/heroku-deploy@v3.0.5
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        health_check: https://example.herokuapp.com/health   # 👈🙏
```

By default, the Application error screen returns 503.

<img width="550" alt="Screenshot 2020-07-02 at 3 04 29 PM" src="https://user-images.githubusercontent.com/1856992/86413521-4485be80-bc76-11ea-8532-76149484eeaf.png">
<img width="335" alt="Screenshot 2020-07-02 at 3 04 25 PM" src="https://user-images.githubusercontent.com/1856992/86413527-464f8200-bc76-11ea-9ab8-b8bfc87506b0.png">
