### ISSUE TITLE
Failing to deploy.

### ISSUE THREAD

**Issue by kraikov** [AkhileshNS/heroku-deploy#24]
Hello. 

My workflow file is the following:

```
name: Deploy

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.3.6
        with:
          branch: "master"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
```

The error I'm receiving in the logs is this:

![image](https://user-images.githubusercontent.com/7030722/88296185-07f23380-cd07-11ea-9e40-4dad1d76c653.png)
