### ISSUE TITLE
Deployment failed due to: 'Push rejected, cannot delete master branch'

### ISSUE THREAD

**Issue by lexwebb** [AkhileshNS/heroku-deploy#26]
To preface im very new to heroku, it is my first time using it for a project.

I'm trying to publish a node app to heroku, the usefull parts of my main.yml can be found below;

When built my app ends up in a folder in the root called 'build'. So im using the appdir parameter of the heroku-deploy.

```
name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node-version }}

      - name: Setup
        run: |
          mkdir -p build/public
      
      <build steps here>

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: battlographer
          buildpack: heroku/nodejs
          appdir: build
```

Now when i run my action i get the following error message/logs at the deploy stage

```
##[group]Run AkhileshNS/heroku-deploy@v3.4.6
with:
  heroku_api_key: ***
  heroku_email: ***
  heroku_app_name: ***
  buildpack: heroku/nodejs
  appdir: build
  branch: HEAD
  dontuseforce: false
  usedocker: false
  docker_heroku_process_type: web
  delay: 0
##[endgroup]
Created and wrote to ~/.netrc
Successfully logged into heroku
Added git remote heroku
heroku: Press any key to open up the browser to login or q to exit: 1/66 (0) [0]
2/66 (1) [0]
...
66/66 (65) [0]
No new revisions were found
remote: 
remote: !	Push rejected, cannot delete master branch        
remote: 
To https://git.heroku.com/***.git
 ! [remote rejected] master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/***.git'

            Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 
            (If you want to avoid this, set dontuseforce to 1 in with: of .github/workflows/action.yml. 
            Specifically, the error was: Error: Command failed: git push  heroku `git subtree split --prefix=build HEAD`:refs/heads/master
1/66 (0) [0]
...
66/66 (65) [0]
No new revisions were found
remote: 
remote: !	Push rejected, cannot delete master branch        
remote: 
To https://git.heroku.com/***.git
 ! [remote rejected] master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/***.git'

        
1/66 (0) [0]
...
48/66 (47) [0]
##[error]Error: Command failed: git push --force heroku `git subtree split --prefix=build HEAD`:refs/heads/master
1/66 (0) [0]
...
66/66 (65) [0]
No new revisions were found
remote: 
remote: !	Push rejected, cannot delete master branch        
remote: 
To https://git.heroku.com/***.git
 ! [remote rejected] master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/***.git'

49/66 (48) [0]
...
66/66 (65) [0]
No new revisions were found
remote: 
remote: !	Push rejected, cannot delete master branch        
remote: 
To https://git.heroku.com/***.git
 ! [remote rejected] master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/***.git'
```

Any idea whats going on here?

From some googling it looks like maybe it could be a login issue with heroku, or possibly an issue with remote branch creation.

**Comment by AkhileshNS** [comment]
Heroku generally pushes the latest commit via Git for deployment. So it might just be that you simply haven't committed any of your changes after building them. So try adding a step that does something like **git add -A && git commit -m "UPDATED CODE"**  and see if maybe that'll help.

Also try adding the conplete url to your buildpack in the option and seeing if that makes any difference

**Comment by lexwebb** [comment]
My builds are being triggered by got commits on GitHub. Is that not enough? Or do you mean a commit to herokus git?

**Comment by AkhileshNS** [comment]
If you're making any changes to your project within GitHub Actions, you'll need to commit them as well. So you could do something:-

```yaml
name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node-version }}

      - name: Setup
        run: |
          mkdir -p build/public
      
      <build steps here>

      - run: git add -A && git commit -m "Updated code" # <- Add this line

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: battlographer
          buildpack: heroku/nodejs
          appdir: build
```

Essentially changes to your project within GitHub Actions might not be committed and Heroku might complain that you're branch is behind.

**Comment by lexwebb** [comment]
Thanks for the suggestion, it almost worked! I also was required to set the git username and email for the commit, of which i used some dummy values:

```
      - run: git config user.email "battlographer@github.com"
      - run: git config user.name "Github"
      - run: git add -A && git commit -m "Updated code"
```

It is also worth mentioning i had to ensure the folder i was building into was not git ignored.

Thanks for the great action!

**Comment by OmarSalah26** [comment]
i tried these solution but still have same problem , cay you help me ?

**Comment by OmarSalah26** [comment]
I solved it ,

by create runtime.txt file and put on this file python-3.7.11 as the version of python i want

app.py
Procfile
requirements.txt
runtime.txt

**Comment by PietroRove** [comment]
Hi have same error. I tried to add this line of code 

` run: git add -A && git commit -m "Updated code" # <- Add this line`

but I obtain a message that there is nothing to commit and so, I remove the line. This is my yaml file:

```
name: Deploy

on: [push]
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm i
        
      - name: test
        run: npm run test-git

      - name: Setup
        run: mkdir -p dist

      - name: build
        run: npm run build-full
                
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "heroku-app-name" #Must be unique in Heroku
          heroku_email: "myemail@email.com"          
          appdir: "dist"

```
