### ISSUE TITLE
'heroku' does not appear to be a git repository

### ISSUE THREAD

**Issue by szekelydavid92** [AkhileshNS/heroku-deploy#27]
Hi,

I get this error but I have no idea why. I don't use heroku branch anywhere I just want to deploy my master branch.
Could you please have a look if it's something I miss or a real issue?

--->
 * [new branch]      YYY -> YYY
 * [new tag]         v1.0.0     -> v1.0.0
Created and wrote to ~/.netrc
Successfully logged into heroku
heroku: Press any key to open up the browser to login or q to exit:  ›   Warning: heroku update available from 7.42.6 to 7.42.8.
Added git remote heroku
heroku: Press any key to open up the browser to login or q to exit: fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
            Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 
            (If you want to avoid this, set dontuseforce to 1 in with: of .github/workflows/action.yml. 
            Specifically, the error was: Error: Command failed: git push heroku master:refs/heads/master 
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists. <---

My workflow file:
--->
name: Heroku deploy
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.4.6
      with: 
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "XXX-heroku"
        branch: "master"
        dontuseforce: 1 <---

**Comment by adefemi171** [comment]
thI think donotuseforce should either be true or false and also in your workflow you did not set the mail option and from the docs it is required

**Comment by AkhileshNS** [comment]
Hey sorry for the late reply. As @adefemi171 pointed out, you will need to set an option for "heroku_email", this is required because that's the account in which the dyno will be created.

```yml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "YOUR APP's NAME" 
          heroku_email: "YOUR EMAIL" # <- THIS IS REQUIRED
```

Also you don't need to specify "branch" and "dontuseforce", the default for both of these will serve you fine. The way Heroku publishes your app is by adding a git remote that points to a git repository managed by Heroku, hence you might see something like `git push heroku master` in the logs, and by default Heroku will push the master  branch so you don't need to worry about that.

Good luck

**Comment by szekelydavid92** [comment]
@adafemi171, @AkhileshNS thank you for the clarification. I removed branch and dontuseforce and added email and it works like charm. Thanks.

**Comment by madhums** [comment]
Does not work. Have the same problem https://github.com/nvcsocialchange/web/actions/runs/763410356

```yml
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          procfile: "web: npm start"

```
