### ISSUE TITLE
New file added in workflow runtime is not deployed

### ISSUE THREAD

**Issue by jsdaniell** [AkhileshNS/heroku-deploy#30]
Considering my workflow file:

```
name: Heroku CI - CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14.6'
      - run: cd src && go mod vendor
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@0.4.0
        with:
          name: "devdatatools-firebase-adminsdk.json"
          object: ${{ secrets.CREDENTIALS_OBJECT }}
          dir: "src/"
      - run: cd src && git config --global user.email "jose.daniell@outlook.com" && git config --global user.name "jsdaniell" && git add . && git commit -a -m "Deploy Heroku Commit"
      - run: cd src && ls
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "dev-data-tools-api-golang"
          heroku_email: "jose.daniell@outlook.com"
          appdir: "src"
```

The problem is that, the file `devdatatools-firebase-adminsdk.json` was created and commited but is ignored on the heroku deployed, as if was not created, but on `cd src && ls` the file was there, there's not gitignore on my `src` repo so this is not the problem. I would like to understand how works the heroku action on my `src` folder.

**Comment by jsdaniell** [comment]
For certified that the file was not in the heroku repo I downloaded my repo from heroku and the file was not there.

**Comment by AkhileshNS** [comment]
Hey, regarding the working of the action in your src folder, the gist of it is that the action runs this command  

```bash
git push heroku \`git subtree split --prefix=${appdir} HEAD\`:refs/heads/master
```

if the appdir property is set. So I'm wondering if for some reason the change isn't being registered because you are adding and committing the file from within the appdir instead of the repo, so try changing this line

```yaml
- run: cd src && git config --global user.email "jose.daniell@outlook.com" && git config --global user.name "jsdaniell" && git add . && git commit -a -m "Deploy Heroku Commit"
```

to this

```yaml
- run: git config --global user.email "jose.daniell@outlook.com" && git config --global user.name "jsdaniell" && git add . && git commit -a -m "Deploy Heroku Commit"
```

I don't think there is a need to cd into the folder since you're just making a commit to the main repository anyway. Lemme know if that helps and also if possible attach the logs that you get from the action for better reference

**Comment by jsdaniell** [comment]
I got deployed correctly, the case is that I have to add forced the .json file on runtime, because they are in the .gitignore of the root folder, what was intentional, in the final my file now is this:

```
name: Heroku CI - CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14.6'
      - run: cd src && go mod vendor
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@0.8.0
        with:
          name: "devdatatools-firebase-adminsdk.json"
          object: ${{ secrets.CREDENTIALS_JSON }}
          dir: "src/"
      - run: git config --global user.email "jose.daniell@outlook.com" && git config --global user.name "jsdaniell" && git add . && git add --force src/devdatatools-firebase-adminsdk.json && git status && git commit -a -m "Deploy Heroku Commit"
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "dev-data-tools-api-golang"
          heroku_email: "jose.daniell@outlook.com"
          appdir: "src"
```

I will add this commit of file automatically on the create-json action, as a optional parameter to set false, but in general all is fine now, very thankfull for the support, and you are alright, the commit action have to be in the root, because they catch of HEAD of the repository. Very, very thanks! I'm very grateful for your support!
