### ISSUE TITLE
Pushing changes from a different branch to Heroku

### ISSUE THREAD

**Issue by adefemi171** [AkhileshNS/heroku-deploy#32]
Hi, following the Github action implementation I have this in my yml
    - name: Login to Heroku and deploy
      uses: akhileshns/heroku-deploy@v3.4.6
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        branch: "master"

Am trying to push from a different branch to **master on Heroku**, got this error at first: _error: src refspec master does not match any_ then later got this: _fatal: empty ident name (for <runner@fv-az20.kpwltci0mcyunckd222hihihaa.gx.internal.cloudapp.net>) not allowed_

**Comment by AkhileshNS** [comment]
Hey @adefemi171, could please send your entire github action yaml file and a picture of the entire logs for better reference.

And also, by default the action will always push to the master branch on Heroku, if you want to push from a different branch of your repository then you'll need to specify that in the **branch** property. So something like this:

```yml
branch: "custom-branch-name"
```

**Comment by adefemi171** [comment]
Thanks for your response, the Github action YAML file can be found [here](https://github.com/WuraLab/NigeriaApi/blob/heroku-auo-deployment-action/.github/workflows/ci.yml). And also the name of the branch am pushing to on Heroku is **Master**

**Comment by AkhileshNS** [comment]
I assume you want to deploy from the **heroku-auo-deployment-action** branch since that is the one which has the procfile.

So try changing the **branch** property to

```yaml
branch: "heroku-auo-deployment-action"
```

And just to clarify the **branch** property corresponds to the branch of your local repo not the Heroku repo, Also just to confirm, have you set your GitHub secrets?

**Comment by adefemi171** [comment]
I did change the branch name and getting this new error:
***** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <runner@fv-az58.1trw5hdeersubfizq0lxfvarta.cx.internal.cloudapp.net>) not allowed
##[error]Error: Command failed: git add -A && git commit -m "Added Procfile"

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <runner@fv-az58.1trw5hdeersubfizq0lxfvarta.cx.internal.cloudapp.net>) not allowed**

**Comment by AkhileshNS** [comment]
Try changing your workflow file to this and see if that helps

```yml
name: Node.js CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
          npm install
    - run: git config --global user.name "adefemi171" && git config --global user.email "adefemi171@gmail.com" # Added this
    - name: Login to Heroku and deploy
      uses: akhileshns/heroku-deploy@v3.4.6
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        branch: "heroku-auo-deployment-action"
        procfile: "web: npm start"
        healthcheck: "https://nigeria-api-backend.herokuapp.com/health"
```
I know you have already placed these two lines before but I think position might play a factor here
