### ISSUE TITLE
Problem in Enviromental Variables

### ISSUE THREAD

**Issue by uinstinct** [AkhileshNS/heroku-deploy#33]
I have a lot of enivormental variables that I need to push to heroku.
I have stored all these variables in an encrypted `.env.gpg` file which I am later decrypting in one of the steps and put it in the folder where the heroku action will take place.
I need to pass this decrypted `.env` file to heroku.
How can I do this? 

```yaml
name: Frontend Deploy

on:
  push:
    branches:
      - autodeploy

jobs:
  deploytoheroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt frontend.env
        run: ./.github/scripts/frontend_decrypt.sh
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.NEW_HEROKU_API_KEY}}
          heroku_app_name: "myapp"
          heroku_email: "email@email.com"
          branch: autodeploy
          appdir: frontend
      - run: echo "Deployed"
```
