### ISSUE TITLE
all env file variables not passing

### ISSUE THREAD

**Issue by uinstinct** [AkhileshNS/heroku-deploy#37]
I am trying to put my env file _(decrypted during workflow action)_ but **this action is only taking the first variable**.

Workflow is not failing but the application crashes due to missing env variables.

My workflow file is like this:

```yml
name: Backend Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  backendDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          DECRYPTER_PASSPHRASE: ${{secrets.DECRYPTER_PASSPHRASE}}
        run: >
          ./.github/scripts/backend_decrypt.sh
      - run: |
          cat backend/.env
          pwd
          ls -a
          ls backend/
      - uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "my-app"
          heroku_email: "myemail@mail.com"
          branch: master
          appdir: backend
          env_file: ".env"
      - run: |
          ls -a
          echo "Deployed"
```

The enviromental variables are correctly decrypted and saved in the `.env` file

This is step `cat backend/.env` from the above workflow

![env variables shown](https://user-images.githubusercontent.com/61635505/94651689-7f030400-0316-11eb-958b-c10945d7622b.png)

But, **only the first variable is passed**

![only 1 variable is passed](https://user-images.githubusercontent.com/61635505/94652270-5c251f80-0317-11eb-91da-ca2dbfc99825.png)
