### ISSUE TITLE
Missing files on push?

### ISSUE THREAD

**Issue by Fradantim** [AkhileshNS/heroku-deploy#39]
Hi there!

I'm pretty sure this is not an issue, but I'm a trully lost on GitHub Actions and the Heroku deploy pipeline.

I built a main.yml workflow which goes like

```
name: CI_COMPILE_DEPLOY_HEROKU

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run compile-web.sh
        run: sh ./compile-web.sh

      - uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "myHerokuAppName"
          heroku_email: "myEmail@gmail.com"
```

The `compile-web.sh` file builds an application which is in a subfolder. After it's execution new folders and files are created, the important file is.
`(Repository)/myApp/target/myApp.jar`

In the repository's root there's a Procfile so Heroku knows where to find the compiled file. Goes like this.
`java $JAVA_OPTS -jar myApp/target/myApp.jar $JAR_OPTS`

In the Actions output i can see the build and deploy process ends well, and Heroku gets notified of the change, but it fails with an error:
`app[web.1]: Error: Unable to access jarfile myApp/target/myApp.jar`

On my PC I execute `heroku run bash` followed by `ls myApp/` and not even the `myApp/target/` folder exists.

Is this an expected behavior? If so, is there a way I can add the mentioned jar file in the heroku push?

Thanks in advance!

**Comment by AkhileshNS** [comment]
Hey, so the way Heroku deployments work is that heroku creates a remote on your git repository called "heroku" which points to one of the heroku's hosted repos. And during deployment, all heroku is doing is running the command `git push heroku master`. So when you deploy to heroku, you aren't really deploying the folder as such, rather your deploying it's latest commit. Since the shell command you're running is creating a file which is not committed, it isn't being deployed to heroku.

To fix this, you can just change your action to this

```yaml
name: CI_COMPILE_DEPLOY_HEROKU

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run compile-web.sh
        run: sh ./compile-web.sh

      # Add this line
      - run: git config user.name "USERNAME" && git config user.email "EMAIL" && git add -A && git commit -m "Updated Code"

      - uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "myHerokuAppName"
          heroku_email: "myEmail@gmail.com"
```

This seems to be a pretty common issue as it's happening to a lot of people which is why I'm planning on adding some kind of fix for it in the upcoming release so once that comes, you won't have to worry about this. But until then, if you're ever changing your repo inside actions before using heroku-deploy, be sure to commit your files first (within the actions environment itself)

**Comment by Fradantim** [comment]
@AkhileshNS I can't thank you enough, added those four commands in another shell file and referenced it on the main.yml. Worked like a charm! Last push went perfectly from my terminal, to launching Github Actions to deploying to heroku.

In the end everything looked like this:
main.yml

```
name: CI_COMPILE_DEPLOY_HEROKU

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run compile-web.sh
        run: sh ./compile-web.sh

      # This lines were added
      - name: Run add-compiled-to-git.sh
        run: sh ./add-compiled-to-git.sh

      - uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "myHerokuAppName"
          heroku_email: "myEmail@gmail.com"
```

And add-compiled-to-git.sh:
```
#!/bin/sh

git config user.name "USERNAME"

git config user.email "EMAIL"

git add -f myApp/target/myApp.jar

git commit -m "New compilation."
```

-f flag because it's explicitly ignored.

Will close with this comment
Thanks again!
