### ISSUE TITLE
Edit files before pushing/deploy

### ISSUE THREAD

**Issue by fabioaraujo121** [AkhileshNS/heroku-deploy#42]
Olá! 🤙

I have to edit some files before pushing to Heroku and I need to push these edited files.

The action goes well (no errors), but the files pushed still there and not changed...

Am I missing something? 🤔

Here's my action:

```yaml
name: CI - Production

on:
  push:
    branches: [ production ]

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Removing Docker
        run: |
          rm -f docker-compose.yml
          rm -f Dockerfile

      - name: Writing credentials
        run: |
          echo "${{ secrets.PRODUCTION_MASTER_KEY }}" > ./config/master.key
          echo "${{ secrets.PRODUCTION_CREDENTIALS }}" > ./config/credentials.yml.enc

      - name: Pushing to production
        uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{ secrets.PRODUCTION_HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.PRODUCTION_HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.PRODUCTION_HEROKU_EMAIL }}

```
