### ISSUE TITLE
Is it possible to deploy docker from github packages or any other docker registry?

### ISSUE THREAD

**Issue by christian-draeger** [AkhileshNS/heroku-deploy#45]
In my project i publish a docker image to github packages (githubs docker registry) using the `docker/build-push-action@v1` action because i need it to be published there anyway. Currently my github actions pipeline builds the docker image a second time when using the heroku deploy action for docker, which looks a bit redundant to me in that case.

is it possibile to just pass a docker image name?

this would also be handy if you just want to deploy some docker image to heroku that you are not maintaining yourself

**Comment by AkhileshNS** [comment]
I'm not quite sure why the docker image is getting built a second time because of the Heroku-Deploy action, since I don't see why Heroku would need the image to be built before uploading it to Heroku (It would make more sense for it to be built at Heroku), so maybe the logs you're seeing is the image being built on Heroku's servers and Github Actions pipeline although I'm not entirely sure.

If possible could you send your workflow file here. That might help a little

**Comment by AkhileshNS** [comment]
Hey sorry for the late response. Regarding your issue, from what research I've done, it doesn't look like you can just pass a docker image directly through the CLI. If you want to deploy images that you've already built to Heroku, you have two options:-

1) One is to use the docker cli to directly push an existing image to Heroku's registry and then use the Heroku CLI to create a release. (You can read more about that [here](https://devcenter.heroku.com/articles/container-registry-and-runtime#pushing-an-existing-image)). This is a bit of tedious process that also requires you to login to docker but you can do this using in GitHub Actions like so:-

```yaml
name: Deploy

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "" 
          heroku_email: "YOUR EMAIL"
          justlogin: true
      - run: |
          heroku container:login
          heroku create <APPNAME> # After you do this, you'll need to remove this command so you're not recreating the app
          docker login --username <USERNAME> --password ${{secrets.DOCKER_PASSWORD}}
          docker tag <image> registry.heroku.com/<APPNAME>/web
          docker push registry.heroku.com/<APPNAME>/web
          heroku container:release web --app <APPNAME>
```

2) Alternatively you can create something called a heroku.yml file in your project and specify in that the location of your Dockerfile like so (Read more about this [here](https://devcenter.heroku.com/articles/build-docker-images-heroku-yml)) :-

```yaml
build:
  docker:
    web: Dockerfile # <- This is the path to your Dockerfile
```

Doing it this way doesn't actually deploy an existing image, it just builds the image on Heroku instead of in your Github Actions pipeline. You can deploy it this way by using the following GitHub Actions workflow:

```yaml
name: Deploy

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "" 
          heroku_email: "YOUR EMAIL"
          justlogin: true
      - run: |
          heroku create <APPNAME> # After you do this, you'll need to remove this command so you're not recreating the app
          # heroku git:remote --app <APPNAME> # You'll need to uncomment this line after your app is created 
          heroku stack:set container
          git push heroku master
```

Atleast for the moment, I'm not sure if I want to incorporate either of these two to the Heroku-Deploy action as options since they both add some complexity to the App. The first approach would require users to also provide their Docker Password (something which can change more often than an API KEY) to the action and the second approach provides no real benefit since there isn't any real difference between whether the image is being built in heroku or in the GitHub Actions pipeline. (And in your specific usecase, the image would be built twice anyway)

So I'm not sure if I'll add this as an option for the moment but if more people need this usecase then I might consider it. But for now, let me know if either of the above solutions helped you and if necessary I can find some way to make this easier for you.
