### ISSUE TITLE
How to set region

### ISSUE THREAD

**Issue by christian-draeger** [AkhileshNS/heroku-deploy#46]
Using the action will deploy a container to herokus default region (us). is it possible to pass `--region eu` to `heroku create` command?

**Comment by AkhileshNS** [comment]
That should be simple. I'll add that as a feature by today, In the meantime, you can do something like this to get by

```yaml
name: Deploy

on:
  push:
    branches:
      - master # Changing the branch here would also work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "" 
          heroku_email: "YOUR EMAIL"
          justlogin: true
      - run: heroku create <APPNAME> --region eu
```

The justlogin flag will allow you to run any command you want on Github Actions while authenticated to Heroku

**Comment by christian-draeger** [comment]
works like a charme 👍 
having it es extra feature is awesome. thanks for your effort  🥇

**Comment by AkhileshNS** [comment]
Hey sorry it took so long but you should be able to specify the region now in the Action

```yaml
name: Deploy

on:
  push:
    branches:
      - master # Changing the branch here would also work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "" 
          heroku_email: "YOUR EMAIL"
          region: "dublin" # <- Example
```
