### ISSUE TITLE
Deploy to Multiple Heroku Environments

### ISSUE THREAD

**Issue by akshayKrSingh** [AkhileshNS/heroku-deploy#47]
Using the action only deploys to one environment. Is there a way to specify the environment of an app during deployment?

Reference: [Heroku Multiple Environments](https://devcenter.heroku.com/articles/multiple-environments)

**Comment by AkhileshNS** [comment]
Hey @akshayKrSingh, while this could certainly be done. It's kind of redundant since you would usually only use this if you were on your local machine. Keep in mind, when you create a staging environment using the Heroku Cli, all you're doing is just creating another Heroku App and adding it as a remote called "staging" (or "production" etc). 

![heroku environments](https://user-images.githubusercontent.com/21128574/102874182-200de080-4468-11eb-935d-78c1aafcbf4f.png)

This makes sense on your local machine where having each git remote represent each heroku app makes sense. But in GitHub Actions, you could just create two workflow files and do something like this:-

_/.github/workflows/staging.yml_
```yaml
name: Staging Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8 #
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "YOUR STAGING APP's NAME"
          heroku_email: "YOUR EMAIL"
```

_/.github/workflows/production.yml_
```yaml
name: Production Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8 #
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "YOUR PRODUCTION APP's NAME"
          heroku_email: "YOUR EMAIL"
```

And you could further specify different trigger rules for each one (See this [link](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows)). Maybe even have each workflow deploy only on push to a specific branch say "staging" or "production" and you'll get basically the same effect as having multiple environments to work in with the benefit of it being easier to share since people can just clone the repo and get the branches with it
