### ISSUE TITLE
Healthcheck doesnt accept env vars

### ISSUE THREAD

**Issue by b1go** [AkhileshNS/heroku-deploy#48]
I have this configuration:
```
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${HEROKU_APP_NAME}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          healthcheck: ${HEROKU_APP_HC}
          checkstring: ok
          delay: 10
          rollbackonhealthcheckfailed: true
```
while heroku_app_name and other vars accept  an env var, healthcheck doesn't and fails

**Comment by AkhileshNS** [comment]
Hey @b1go, sorry but I couldn't quite understand your issue.

From what I can discern from your configuration, I think maybe you're trying to pass HEROKU_APP_NAME and HEROKU_APP_HC as env variables which I think might be a little redundant. My suggestion to you is to either pass them via GitHub secrets like so

```yaml
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          healthcheck: ${{secrets.HEROKU_APP_HC}}
          checkstring: ok
          delay: 10
          rollbackonhealthcheckfailed: true
```

or pass them directly into the configuration as strings

```yaml
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "HEROKU_APP_NAME"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          healthcheck: "HEROKU_APP_HC"
          checkstring: ok
          delay: 10
          rollbackonhealthcheckfailed: true
```

Lemme know if this helps

**Comment by b1go** [comment]
I am configuring a boilerplate, and trying to avoid unnecessary configuration so I am using {prefix + repo_name} for heroku_app_name and this works!

But for the healthcheck url, when I pass an env var I get an error:
```
Invalid URL : ${HEROKU_URL}
```

**Comment by AkhileshNS** [comment]
I assume you're passing env variables like so:

```yaml
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${HEROKU_APP_NAME}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          healthcheck: ${HEROKU_APP_HC}
          checkstring: ok
          delay: 10
          rollbackonhealthcheckfailed: true
        env:
          HEROKU_APP_NAME: "value"
          HEROKU_APP_HC: "value"
```

in which case it might that you're passing a path relative to your app name's url like "/health" or the like. Make sure that you're passing a complete URL to the action. If that isn't the case, is there any way you can log the env var since "Invalid URL" might imply that the variable is still being passed.
