### ISSUE TITLE
Creating new apps in a specific organization name 

### ISSUE THREAD

**Issue by b1go** [AkhileshNS/heroku-deploy#49]
I tried to deploy a new project, it was created but under my personal profile. Is there way to specify what organization name to create under its name

**Comment by AkhileshNS** [comment]
At the moment no. But that should be easy enough to add. In the meantime, after you deploy your app, you can just transfer it to whatever team you're working with using

```
heroku apps:transfer <TEAMNAME> --app <APPNAME>
```

After that, the next time Heroku-Deploy runs, it should automatically just deploy it to the team's projects so long as your API Key has the permissions for it. (Read more about that [here](https://devcenter.heroku.com/articles/develop-orgs#adding-apps-to-an-enterprise-team))

**Comment by assem-ch** [comment]
I prefer to keep things automated to not intervene manually for every new app. If the app is created in the organization account, other org admins can continue the configuration without my intervention. I see this feature as important.

**Comment by b1go** [comment]
I prefer things to be automated , so no need to intervene manually for every app created.

**Comment by AkhileshNS** [comment]
Hey, so I've added an option called "team" that should allow you specify to what team you are deploying to. 

```yaml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8-beta
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "YOUR APP's NAME" 
          heroku_email: "YOUR EMAIL"
          team: "THE TEAM's NAME"
```

Note. that it says beta because I don't have the means to test this since I don't have an enterprise Heroku account. So if you can confirm to me that this works fine (or I'll figure something out in a few days), I can make a stable release instead.
