### ISSUE TITLE
Is there a more efficient way to do this?

### ISSUE THREAD

**Issue by wootwoot1234** [AkhileshNS/heroku-deploy#5]
Is there a better way to do this so that it combines some of the steps?  Below is an example of my setup but I have 10 servers, I commit often and my github minutes are getting used up fast!  :)

Thanks!

    name: Deploy Beta

    on:
      push:
        branches:
          - beta

    jobs:
      push0:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: akhileshns/heroku-deploy@v3.0.0
            with:
              branch: "beta"
              heroku_api_key: "asdf"
              heroku_app_name: "asdf-beta1"
              heroku_email: "asdf@asdf.com"
      push1:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: akhileshns/heroku-deploy@v3.0.0
            with:
              branch: "beta"
              heroku_api_key: "asdf"
              heroku_app_name: "asdf-beta2"
              heroku_email: "asdf@asdf.com"

**Comment by AkhileshNS** [comment]
Its hard to say how much more efficient I can make this. The most expensive part of the action is the actual deployment and I've found that it tends to vary wildly depending on things like the language you're using. 

For example: I've found that my NodeJS based apps can be deployed in as little as 10 seconds (I'm talking only about the time taken by the action, the overall time was more like 21 seconds) but my csharp based apps take upto 1 minute 20 seconds to deploy sometime (overall is 1 minute 23 seconds)

That said, a few tips I can offer to try to optimize your workload would be
- try switching to actions/checkout@v1. I've found in some cases that v1 performs better than v2. (sometimes by a difference of upto 8 seconds)
- if you're using a language that takes more time to deploy, try switching to a docker container and see if that helps

Beyond this, a solution thats kind of a hack would be making your repo public and keeping your code safe by either encrypting it and storing the encryption key in github secrets or zipping your folder and storing the zip password in github secrets. Then using either to decrypt or unzip your repo after cloning it before deploying it in github actions. That might look something like this:-
```
name: Deploy Beta

on:
  push:
    branches:
      - beta

jobs:
  push0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: placeholder/decrypt-or-unzip@v1 # This is not an actual action. Just an example
        with:
          unzip-pwd-or-encryption-key: "placeholder"
      - uses: akhileshns/heroku-deploy@v3.0.0
        with:
          branch: "beta"
          heroku_api_key: "asdf"
          heroku_app_name: "asdf-beta1"
          heroku_email: "asdf@asdf.com"
``` 

And public repos have unlimited minutes. That said this can be a bother if you're in a team, or want to view your code on github and its kind of a serious abuse of github's services but I'll leave the answer with you all the same.

Aside from all of this, I will try and optimize the action regardless but don't hold any expectations in that direction since I have very little ideas in how I'm to go about it.

Hope this answer helps. Good luck
