### ISSUE TITLE
Setup addons for new created projects

### ISSUE THREAD

**Issue by b1go** [AkhileshNS/heroku-deploy#50]
Can we have a way to setup addons for newly created projects the same way done by `heroku.yml`-> setup phase: https://devcenter.heroku.com/articles/build-docker-images-heroku-yml#setup-defining-your-app-s-environment

**Comment by AkhileshNS** [comment]
I think you could just define a heroku.yml file and specify the addons in there. When deployed Heroku should automatically just read it for you. But make sure that you specify a "run" that works similar to your Procfile since according to the docs, Heroku favors the heroku.yml's "run" over anything specified in the Procfile. (Read more about that [here](https://devcenter.heroku.com/articles/build-docker-images-heroku-yml#setup-defining-your-app-s-environment))

**Comment by assem-ch** [comment]
Okay, I think this can be done manually, but if #49  can be done so any org admin can do it not just me.

**Comment by b1go** [comment]
Okay, I think this can be done manually, but if #49  can be done so any org admin can do it not just me.

**Comment by AkhileshNS** [comment]
Sure thing. I'll setup an option to make that possible by the end of the day. Something along the lines of 

```yaml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "YOUR APP's NAME" #Must be unique in Heroku
          heroku_email: "YOUR EMAIL"
          team: "TEAM NAME"
```
