### ISSUE TITLE
.npmignore

### ISSUE THREAD

**Issue by SpencerKaiser** [AkhileshNS/heroku-deploy#56]
Does this action respect `.npmignore` in terms of what's deployed to Heroku? If it does, is there anything special we need to do to configure it?

**Comment by AkhileshNS** [comment]
I don't think the Action respects `.npmignore`. Instead it might rather reference `.gitignore` to decide what files and folders should be deployed to Heroku. (Mainly because Heroku uses git)

**Comment by SpencerKaiser** [comment]
I guess I really just need to commit to docker. My issue is that my project is in TS and I'd rather it use the compiled project in from within my GitHub Action instead of pushing the whole repo and building in Heroku. At the end of the day, I guess it really doesn't matter... I'll just stick to building in Heroku

And for what it's worth, it appears this action works for projects that don't use docker as well!

**Comment by AkhileshNS** [comment]
So I guess what you're kind of looking for is a `herokuignore` file so to speak. One solution that does come to mind is to maybe compile the project, add the TS files dir to .gitignore  and then push the project within the action. So something like this.

```yaml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     - run: |
          npm run build # runs 'tsc'
          echo "NAME OF DIR WITH TS FILES" >> .gitignore
          git config user.name "USERNAME" 
          git config user.email "YOUR EMAIL"
          git add -A
          git commit -m "Added ts files dir to gitignore"
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "YOUR APP's NAME" #Must be unique in Heroku
          heroku_email: "YOUR EMAIL"
```
