### ISSUE TITLE
Error: fatal: not a git repository (or any of the parent directories)

### ISSUE THREAD

**Issue by Agusnez** [AkhileshNS/heroku-deploy#6]
I have a fresh .yml that looks like this:

```
name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.0.0
      with:
        # This will be used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{ secrets.api_key }}
        # Email that you use with heroku
        heroku_email: ${{ secrets.email }}
        # The appname to use for deploying/updating
        heroku_app_name: ${{ secrets.name }}
        branch: "master" 
```

But all my builds fails. It says:

```
##[error]Error: Command failed: git rev-parse --is-shallow-repository
fatal: not a git repository (or any of the parent directories): .git
```

Any ideas that what's happening? It's my first time with GitHub actions. Thanks in advance!

**Comment by Agusnez** [comment]
Okay fixed it with:

```
name: Heroku CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2 #New line!
     - uses: AkhileshNS/heroku-deploy@v3.0.0
       with:
        branch: "master"
        # This will be used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{ secrets.api_key }}
        # Email that you use with heroku
        heroku_email: ${{ secrets.email }}
        # The appname to use for deploying/updating
        heroku_app_name: ${{ secrets.name }}
```

The problem was that I wasn't checking out the git repository.
