### ISSUE TITLE
Error: Command failed: heroku login

### ISSUE THREAD

**Issue by cj** [AkhileshNS/heroku-deploy#61]
Hi, hope your week is going well.

I am currently getting this error:

```
Created and wrote to ~/.netrc
 ›   Warning: Our terms of service have changed: 
 ›   https://dashboard.heroku.com/terms-of-service
Error: Error: Command failed: heroku login
 ›   Warning: Our terms of service have changed: 
 ›   https://dashboard.heroku.com/terms-of-service
 ›   Error: Cannot log in with HEROKU_API_KEY set

 ›   Error: Cannot log in with HEROKU_API_KEY set
```

I have double and tripple checked my `heroku_api_key `, `heroku_app_name` and `heroku_email` and they are all correct.  Was there a change to how the heroku api works recently?

Below is my config:

```
      - name: Deploy Production
        uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        if: contains(github.ref, 'main')
        with:
          heroku_api_key: ${{ env.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME_PRODUCTION }}
          heroku_email: ${{ env.HEROKU_EMAIL }}
          healthcheck: ${{ env.HEROKU_HEALTH_CHECK_URL_PRODUCTION }}
          checkstring: 'ok'
          rollbackonhealthcheckfailed: true
```
