### ISSUE TITLE
fatal: Couldn't find remote ref master

### ISSUE THREAD

**Issue by pedromoraisf** [AkhileshNS/heroku-deploy#63]
Hello,

when trying to deploy, I'm falling into this error:
<img width="787" alt="Captura de Tela 2021-02-08 às 14 48 49" src="https://user-images.githubusercontent.com/55749387/107260570-01b27300-6a1d-11eb-833f-743f3a41ab5a.png">

Environment: 
- I was already deploying automatically via heroku's hook to Github (connect to GitHub)
- The deploy was being configured by the "test" branch (not a main branch)

**Comment by AkhileshNS** [comment]
Hey @pedromoraisf, just to confirm, are you saying that the deployment happens in the test branch of your repository or to the test branch in the heroku repo?

If it's the former, then try adding `branch: test` and if it's the later, try adding `remote_branch: test` and see if that is able to fix your issue

**Comment by pedromoraisf** [comment]
hello
it happens through the branch test of my repository;
I will try the first option here

**Comment by underfisk** [comment]
@AkhileshNS I do have the same issue, i've got only 1 branch in a new repo (to test this github action) named master and only 1 remote master, when i attempt to push it reports that it can't find the remote ref

My action part
```
    - uses: akhileshns/heroku-deploy@v3.10.9
          with:
              heroku_api_key: ${{secrets.HEROKU_API_KEY}}
              heroku_app_name: "<my app name..>"
              heroku_email: "<my super secret email>"
              dontuseforce: true
              branch: master
              remote_branch: master # <- Include this
```
You can try to setup a new app and a new repo and this will happen
