### ISSUE TITLE
Error: Error: Command failed: git push heroku HEAD:refs/heads/main --force

### ISSUE THREAD

**Issue by IshaanOhri** [AkhileshNS/heroku-deploy#68]
Below is the error I received:

<img width="1310" alt="Screenshot 2021-02-19 at 2 05 17 PM" src="https://user-images.githubusercontent.com/39885197/108479278-8920a180-72bb-11eb-9fde-5278190fa3bc.png">

And this is my main.yml file:

```
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Build project
        run: npm run-script build
      - uses: akhileshns/heroku-deploy@v3.11.10 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "git-auto" #Must be unique in Heroku
          heroku_email: "ishaan99ohri@gmail.com"
          procfile: "web: npm start"
```
