### ISSUE TITLE
How to use this action on a subfolder in my repo?

### ISSUE THREAD

**Issue by rohitkrishna094** [AkhileshNS/heroku-deploy#79]
Say I have a subfolder called backend which is a generic node+express app. However I want to apply this action only to that subfolder? I tried using `working-directory` but looks like `working-directory` doesn't work in combination with `uses`. Here is my yaml

```yml
name: Backend deploy to heroku

on:
  push:
    branches:
      - master
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install deps
        working-directory: ./backend
        run: npm i
      - name: Run lint
        working-directory: ./backend
        run: npm run lint
      - name: Run Build
        working-directory: ./backend
        run: npm run build
        env:
          CI: ''
      - name: Deploy to heroku
        working-directory: ./backend #--> this line is failing
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_app_name: 'very-unique-name'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
```
