### ISSUE TITLE
Not logged in even though The ~/.netrc file was already written.

### ISSUE THREAD

**Issue by talentedasian** [AkhileshNS/heroku-deploy#87]
I tried doing the justlogin to true to manually do things on my own with this action but it says that I am not logged in even though the justlogin was succesfull. It even wrote a ~/.netrc file that I also printed out successfully too. 

This is the specific error I got:

```
Error: not logged in
Error: Process completed with exit code 100.
```

This is the result of the action:

```
Run akhileshns/heroku-deploy@v3.12.12
  with:
    heroku_email: lucenaalmirjames123@gmail.com
    justlogin: true
    branch: HEAD
    dontuseforce: false
    dontautocreate: false
    usedocker: false
    docker_heroku_process_type: web
    delay: 0
    rollbackonhealthcheckfailed: false
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/15.0.2-7/x64
Created and wrote to ~/.netrc
```
