### ISSUE TITLE
No images to push

### ISSUE THREAD

**Issue by ndjenkins85** [AkhileshNS/heroku-deploy#98]
- [X] I have read instructions carefully
- [X] HEROKU_API_KEY is in Github secrets
- [X] I have checked the app name
- [X] I have a dockerfile (with copy commands and no adds)
- [X] I have checked open and closed issues

I am using the standard instructions to deploy with addition of `usedocker: true` for my personal website.

```
name: Deploy
# https://github.com/marketplace/actions/deploy-to-heroku#deploy-with-docker

on:
  push:
    branches:
      - master
      - staging/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nickjenkins"
          heroku_email: "xxxx@gmail.com"
          usedocker: true
```

Task fails here with `No images to push`

```
Run akhileshns/heroku-deploy@v3.12.12
Created and wrote to ~/.netrc
 ›   Warning: Our terms of service have changed: 
Successfully logged into heroku
 ›   https://dashboard.heroku.com/terms-of-service
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Added git remote heroku
 ▸    No images to push

            Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 
            (If you want to avoid this, set dontuseforce to 1 in with: of .github/workflows/action.yml. 
            Specifically, the error was: Error: Command failed: heroku container:push web --app nickjenkins 
 ▸    No images to push
```

Typically I use Heroku CLI to push docker image which are created locally. I'm looking to implement automatic deployment with github actions. 

Appreciate any possible support! Hopefully I'm just overlooking something simple.
